// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgMintTokens } from "./types/solt/freezer/tx";
import { MsgFreezeTokens } from "./types/solt/freezer/tx";
import { MsgUnfreezeTokens } from "./types/solt/freezer/tx";


export { MsgMintTokens, MsgFreezeTokens, MsgUnfreezeTokens };

type sendMsgMintTokensParams = {
  value: MsgMintTokens,
  fee?: StdFee,
  memo?: string
};

type sendMsgFreezeTokensParams = {
  value: MsgFreezeTokens,
  fee?: StdFee,
  memo?: string
};

type sendMsgUnfreezeTokensParams = {
  value: MsgUnfreezeTokens,
  fee?: StdFee,
  memo?: string
};


type msgMintTokensParams = {
  value: MsgMintTokens,
};

type msgFreezeTokensParams = {
  value: MsgFreezeTokens,
};

type msgUnfreezeTokensParams = {
  value: MsgUnfreezeTokens,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgMintTokens({ value, fee, memo }: sendMsgMintTokensParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgMintTokens: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgMintTokens({ value: MsgMintTokens.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgMintTokens: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgFreezeTokens({ value, fee, memo }: sendMsgFreezeTokensParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgFreezeTokens: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgFreezeTokens({ value: MsgFreezeTokens.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgFreezeTokens: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgUnfreezeTokens({ value, fee, memo }: sendMsgUnfreezeTokensParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUnfreezeTokens: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUnfreezeTokens({ value: MsgUnfreezeTokens.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUnfreezeTokens: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgMintTokens({ value }: msgMintTokensParams): EncodeObject {
			try {
				return { typeUrl: "/solt.freezer.MsgMintTokens", value: MsgMintTokens.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgMintTokens: Could not create message: ' + e.message)
			}
		},
		
		msgFreezeTokens({ value }: msgFreezeTokensParams): EncodeObject {
			try {
				return { typeUrl: "/solt.freezer.MsgFreezeTokens", value: MsgFreezeTokens.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgFreezeTokens: Could not create message: ' + e.message)
			}
		},
		
		msgUnfreezeTokens({ value }: msgUnfreezeTokensParams): EncodeObject {
			try {
				return { typeUrl: "/solt.freezer.MsgUnfreezeTokens", value: MsgUnfreezeTokens.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUnfreezeTokens: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			SoltFreezer: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;